apiVersion: v1
kind: Service
metadata:
  name: nexops-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nexops-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
