apiVersion: v1
kind: Service
metadata:
  name: nexops-backend
  namespace: nexops
spec:
  selector:
    app: nexops-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
