apiVersion: v1
kind: Service
metadata:
  name: nexops-frontend
  namespace: nexops
spec:
  selector:
    app: nexops-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
