$ErrorActionPreference = "Continue"
. "$PSScriptRoot\_common.ps1"
& "$PSScriptRoot\01-status.ps1"
& "$PSScriptRoot\06-git-check.ps1"
& "$PSScriptRoot\07-kubernetes-check.ps1"
& "$PSScriptRoot\08-argocd-check.ps1"
& "$PSScriptRoot\09-domain-check.ps1"
Write-Host ""
Pass "All safe checks completed. No destructive command was executed."
