#!/usr/bin/env bash
# encode-secrets.sh
# Reads docker/.env and writes kubernetes/backend/secret.yaml (base64 encoded).
# Usage:
#   cp docker/.env.example docker/.env   ← fill in real values first
#   bash scripts/encode-secrets.sh
#   kubectl apply -f kubernetes/backend/secret.yaml
set -euo pipefail

ENV_FILE="docker/.env"
OUT_FILE="kubernetes/backend/secret.yaml"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found."
  echo "Run:  cp docker/.env.example docker/.env"
  echo "Then fill in your real values and re-run."
  exit 1
fi

b64() { printf %s "$1" | base64; }
required() {
  local key="$1"
  if [[ -z "${vals[$key]:-}" ]]; then
    echo "ERROR: $key is required in $ENV_FILE"
    exit 1
  fi
}

declare -A vals
while IFS='=' read -r key val; do
  [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
  val="${val%%#*}"; val="${val//\"/}"; val="${val# }"; val="${val% }"
  vals["$key"]="$val"
done < "$ENV_FILE"

required DATABASE_URL
required DIRECT_URL
required JWT_SECRET
required ADMIN_KEY
required ALLOWED_ORIGIN
required FRONTEND_URL

cat > "$OUT_FILE" << EOF
# Auto-generated by scripts/encode-secrets.sh — do not edit by hand.
# This file is git-ignored. Re-run the script whenever .env changes.
apiVersion: v1
kind: Secret
metadata:
  name: nexops-backend-secret
  namespace: nexops
type: Opaque
data:
  DATABASE_URL: $(b64 "${vals[DATABASE_URL]:-}")
  DIRECT_URL: $(b64 "${vals[DIRECT_URL]:-}")
  JWT_SECRET: $(b64 "${vals[JWT_SECRET]:-}")
  JWT_EXPIRES_IN: $(b64 "${vals[JWT_EXPIRES_IN]:-7d}")
  RESET_TOKEN_EXPIRE_MINUTES: $(b64 "${vals[RESET_TOKEN_EXPIRE_MINUTES]:-30}")
  ADMIN_KEY: $(b64 "${vals[ADMIN_KEY]:-}")
  ALLOWED_ORIGIN: $(b64 "${vals[ALLOWED_ORIGIN]:-}")
  FRONTEND_URL: $(b64 "${vals[FRONTEND_URL]:-}")
  EMAIL_USER: $(b64 "${vals[EMAIL_USER]:-}")
  EMAIL_PASS: $(b64 "${vals[EMAIL_PASS]:-}")
  NOTIFY_EMAIL: $(b64 "${vals[NOTIFY_EMAIL]:-}")
  RESEND_API_KEY: $(b64 "${vals[RESEND_API_KEY]:-}")
  APP_NAME: $(b64 "${vals[APP_NAME]:-NexOps}")
  NODE_ENV: $(b64 "${vals[NODE_ENV]:-production}")
  PORT: $(b64 "${vals[PORT]:-8000}")
  UPLOAD_DIR: $(b64 "${vals[UPLOAD_DIR]:-/uploads}")
  MAX_UPLOAD_SIZE_MB: $(b64 "${vals[MAX_UPLOAD_SIZE_MB]:-10}")
EOF

echo "Done. Written to $OUT_FILE"
echo "Apply with: kubectl apply -f $OUT_FILE"
